### ISSUE TITLE
Link side queries duplicates/merges when using SNMP ifInOctets and ifOutOctets

### ISSUE THREAD

**Issue by tad-david** [knightss27/grafana-network-weathermap#14]
**Describe the problem**
Works as expected when working with queries from Netdata metrics that has their own dimension for received and sent. However when using SNMP where there is a different base query (ifInOctets vs ifOutOctets) the query link side suggester only shows the same result for both sides even with 2 queries. 

Also I checked in the Explore to confirm both Datasets are not wide. 

**To Reproduce**
Steps to reproduce the behavior (if possible):
1. Add SNMP datasource (e.g Prometheus SNMP exporter)
2. Query the data
3. Add nodes and links
4. Select query for link sides
5. See that it only shows duplicate

**Expected behavior**
Expected to get the similar approach as when using Netdata metrics. 

**Screenshots**

Dataset:
<img width="2047" alt="image" src="https://user-images.githubusercontent.com/99338775/179157016-587c7738-53e7-490c-9615-efaa196bc919.png">

Bug:
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/99338775/179160987-1f3677cc-0d95-42df-aa0e-19bbb1c33db6.png">

How it should be:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/99338775/179157074-981f0933-dce0-4c76-b211-c13988f87dee.png">

**VERSIONS! (please complete the following information):**
 - Browser Firefox
 - Grafana Version 9.0.0
 - Plugin Version 0.2.8
 - Additional Versions Prometheus (With Prometheus SNMP exporter)

**Additional context**

**Comment by knightss27** [comment]
Hey there,

First, thanks for using the bug issue formatting!

Second, can you try changing the legend formatting for each of those queries so that they are different? This might be as simple as just adding a "sent"/"received" to the end of the current legend string in the queries' options.

I think this is happening because both queries end up having the exact same legend name, thus the Select component for choosing them gets confused and only ever chooses the first one. Adding those different labels should hopefully fix this. I should look into fixing this but it is also kind of Grafana's fault for how they designed their component.

Let me know if this helps!

**Comment by tad-david** [comment]
Thanks this resolved it, and thanks for a great plugin!
