### ISSUE TITLE
IEC vs SI units for data rate

### ISSUE THREAD

**Issue by hy-ntyni** [knightss27/grafana-network-weathermap#34]
Hi,

it looks like 8373e2af609432938b97d14bf988f19df5dcc81a changed the default data rate units from SI (Gbps etc.) to IEC (Gibps etc.) This is a surprising choice. I think network data rates use SI everywhere, and Wikipedia [seems to agree](https://en.wikipedia.org/wiki/Binary_prefix#Data_transmission_and_clock_rates). My 100G links are now marked with 93.1 Gibps, which seems rather silly. I see this can be overridden per link, but that's a lot of work and I'd much rather change the default. I don't see a way to do that currently, though.

Would it be possible to change the default units to SI and/or make the default configurable?

Thanks for your work on this very useful plugin.

**Comment by knightss27** [comment]
I may just push a quicker update that adds a configurable default, since in general I was somewhat unsure and had frankly thought someone would just say something otherwise (which you have now, so thanks for that).

I'm also working on a feature that brings templated nodes/links to the weathermap, so you can plop down a bunch of links and nodes and simply change how they look / their units / their setup based on some templates you've created (which essentially means much easier defaults for everything), so this should be ironed out even better sooner or later.

**Comment by knightss27** [comment]
I've added new default link units, and the ability to reset all existing links to the default units (since I had been setting the default on each link individually previously, so this is necessary to override that). Will be released within the week with v0.3.4.
