### ISSUE TITLE
uploading background or images 

### ISSUE THREAD

**Issue by 5eb38fd8cdee** [knightss27/grafana-network-weathermap#5]
Hello,

I have the Weathermap running in a test environment and it works quite well.

One feature request would be the possibility of uploading custom backgrounds (other than solid colors) and also upload images onto the map itself (i.e.: a country flag for instance).

Let me know what you think.

Keep up the great work!

**Comment by knightss27** [comment]
Hi there!

Yes, I think this is definitely possible and I will look into adding it in the next version, or at least the custom backgrounds as uploading onto the map itself might take a little more work.

**Comment by knightss27** [comment]
I've added both of these in the latest release! You can set backgrounds by setting the image near where the background options already are, and now if you click on the "icon" accordion when editing a node, you can upload your own. If you just wanted the image for your node, you can simply set the label of the node to be empty and the map will center your image by itself!

**Comment by knightss27** [comment]
Hey, just a heads up on this topic. 

Turns out Grafana doesn't want to promote massive JSON files for dashboards (especially in plugins that are on the community page), and since this feature relies on just sticking the base64 image into the dashboard JSON, it can't continue as is. Thus, I will be disabling this feature for future versions signed for community use. They have told me they are working on a better way to allow for image uploading, so hopefully it comes back soon.

In the meantime, I may start publishing an un-signed / development version of this plugin which can continue to have this feature. Though, this means you will have to deal with using the unsigned plugin of course.
