### ISSUE TITLE
Current speed value's in dashboard config

### ISSUE THREAD

**Issue by EYEVO** [knightss27/grafana-network-weathermap#61]
Currently, every time I exit I get asked to save the dashboard even tho I have not changed anything. When I view the changes, it seems to be hard-coding the current speed values in de dashboard config. I don't see why it should do this since it changes every minute.

**To Reproduce**
edit dashboard and exit without changing anything and view the changelog.
![image](https://github.com/knightss27/grafana-network-weathermap/assets/16328089/cd7c1427-0ebd-42ce-ad88-b6dfdc3ed203)

**Expected behavior**
I should exit without a save prompt because there were no changes.

**VERSIONS:**
 - Browser Edge Version 114.0.1823.58
 - Grafana Version v10.0.1
 - Plugin Version 0.3.6

**Additional context**
Using Zabbix as the source for the data.

**Comment by knightss27** [comment]
Thanks for pointing this out. It was something I had seen before but hadn't spent the time getting to the bottom of. I think that I've fixed it, but need to do some more testing to ensure I haven't accidentally broken something else. I'll close this issue when the update to fix this is released.

Long story short, since I originally wrote this part of the program, Grafana has added better state handling for the panel so some tricks I had implemented to reduce calls to redraw were no longer useful (and this "state written to dashboard JSON" was an outcome of that).

**Comment by knightss27** [comment]
Alright, the new version is out on Grafana (it's v0.4.2). You might have to save your dashboard once (after updating the plugin) for this to fully take effect? But from my testing on the released version I can now update the dashboard to see the new values and leaving or trying to save brings up no new changes.

**Comment by EYEVO** [comment]
Seems to work now, thanks!
