### ISSUE TITLE
Links Side Query not working

### ISSUE THREAD

**Issue by Miccia94** [knightss27/grafana-network-weathermap#7]
Hello,

After some time Side Query stop working.
I cannot no more select the correct query and only wide option is shown.
![image](https://user-images.githubusercontent.com/5357658/169072601-de718a5d-e307-41a8-a494-ab48c51ab235.png)

**Comment by knightss27** [comment]
Is this for all links? and would you mind also posting a screenshot of the query you are using in Grafana? (from the bottom of the edit page).

If you can find any way to reproduce this please let me know.

**Comment by Miccia94** [comment]
Hello,

Yes, this is happening for all links. I'm using Zabbix Metrics as query. This happening as soon as i add a second query to Grafana.

![image](https://user-images.githubusercontent.com/5357658/169225073-297fc7d7-c43d-44fb-805c-ff7d601d4568.png)
![image](https://user-images.githubusercontent.com/5357658/169225190-a1477657-471c-4633-9543-6bddd821b85e.png)

I tried already with wildcards in metric but is still give me wide as only option

![image](https://user-images.githubusercontent.com/5357658/169225358-df6821e1-14d1-4b21-b82a-0b8d6cd204e2.png)

**Comment by knightss27** [comment]
Yes, I think this is related to https://github.com/alexanderzobnin/grafana-zabbix/issues/1341.

The weathermap plugin doesn't support "wide" data formats (where each column is a new time, and each row a new query response), which it seems the Zabbix data source likes to do by default when you have multiple queries for one panel. Thus instead of the weathermap seeing multiple queries, it just sees one as it does not know how to interpret the data. 

Could you try disabling the "data alignment" option for the Zabbix data source (you can see how to do it here: https://alexanderzobnin.github.io/grafana-zabbix/configuration/) and let me know what happens.

Otherwise, this may be more of a Zabbix datasource specific issue than one I can fix.

**Comment by Miccia94** [comment]
Hello,

Disabling data alignment in the metric query seems to fix the issue.

Thanks

**Comment by knightss27** [comment]
Great! Glad I could help.
