### ISSUE TITLE
Clickable link from link.

### ISSUE THREAD

**Issue by davesbell** [knightss27/grafana-network-weathermap#9]
Good morning!

While writing this feature request, I've noticed how overloaded the term link is!

One feature from the cacti weathermaps that I miss is the ability to hover over a link, and see the bandwidth graph for that link pop up.

I appreciate that this is unlikely to be feasible to implement in that way.

Would it be possible to make it so you click a link, and it takes you to a custom dashboard with the variables used to define that link? This way we could click through to a graph of the link.

**Comment by knightss27** [comment]
I have made it so that you can just forward to whatever you'd like for each link. I had actually played around with showing graphs on link hover, and I may even consider this in the future, since if you are passing the panel a bunch of data frames already, there is no reason I couldn't just construct a graph (and I am looking into some ways to maybe just render a whole panel). Until then, you can simply add a "Dashboard Link" to each of the link's sides, which can just be a url. If you'd like to link to specific graphs, you can just click "Share" on that panel in Grafana and then get a URL for it.
